### ISSUE TITLE
https / ssl connection

### ISSUE THREAD

**Issue by zurnet** [dready92/PHP-on-Couch#56]
Is it possible to connect to the couch db using https://   If I try http:// it works fine, but if I try https://  it does not?

**Comment by jrwashbu** [comment]
@zurnet what did you do to get connect to cloudant db using https?  

I'm running into the exact same issue as you stated in your March 14 2014 statement.  If I run my php code from command line it works.  But when I try to access the php via browser (php served up using apache via xampp) I get the Fatal error: Uncaught exception 'InvalidArgumentException' with message 'no data to parse'

Here's simple code example:

<?php
require_once('./lib/couch.php');
require_once('./lib/couchClient.php');
require_once('./lib/couchDocument.php');

$client = new couchClient ('https://<username>:<password>@<host>:443','<dbname>');

// Get all docs
$all_docs = $client->getAllDocs();
echo "Database got ".$all_docs->total_rows." documents.<BR>\n";
foreach ( $all_docs->rows as $row ) {
    echo "Document ".$row->id."<BR>\n";
}
?>

So here's things working via the command line (password clipped for obvious reasons):
![image](https://cloud.githubusercontent.com/assets/13036700/9687866/5d78f8e2-52f1-11e5-9cf9-c7c828e447de.png)

And here's the error seen when accessing via browser:
![image](https://cloud.githubusercontent.com/assets/13036700/9687887/860802d0-52f1-11e5-97d5-3618e2e26ec7.png)

**Comment by zurnet** [comment]
@jrwashbu

The basics of it is you should run couchdb locally and access it via HTTP. On the web server, use HTTPS.  Simply use an IF statement to understand if you're local or on the web.

		if(strpos($_SERVER["SERVER_NAME"], '.loc') == true){
			$client = new couchClient ('http://USER_NAME:PASS_WORD@127.0.0.1:5984','YOUR_DB_NAME');
		} else {
			$client = new couchClient ('https://USER_NAME:PASS_WORD@CLOUDANT_USER_NAME.cloudant.com','YOUR_DB_NAME');
		}

**Comment by 8418128** [comment]
hello all!
im getting the same issue "no data to parse" in laravel 5 and i dont know how to solve or what im doing bad..
require_once app_path().'\Couch\lib\couch.php';
    require_once app_path().'\Couch\lib\couchClient.php';
    require_once app_path().'\Couch\lib\couchDocument.php';

    $client = new couchClient ('https://X:Y@X.cloudant.com:443','users');
    $all_docs = $client->getAllDocs();
    echo "Database got ".$all_docs->total_rows." documents.\n";
    foreach ( $all_docs->rows as $row ) {
        echo "Document ".$row->id."\n";
    }

**Comment by zurnet** [comment]
- confirming you can hit the url directly and get data returned?  
- try setting up another cloudant account and see if you run into the same error? (make sure you pick a different cluster/location)

**Comment by 8418128** [comment]
Thanks for the awnser zurnet;
I've created another account in different location, when i put the url in the browser it prints {"couchdb":"Welcome","version":"1.0.2","cloudant_build":"2530"} but the same exception "no data to parse" when i run the php code.
If i run var_dump with the $raw_data before the exception it prints "boolean(false)", and if i var_dump the response calling the url by curl via php a get the same "boolean(false)".

**Comment by zurnet** [comment]
You've created a db, a view of some sort and adding some records already yes?

**Comment by 8418128** [comment]
![image](https://cloud.githubusercontent.com/assets/15995221/11962440/18c5183a-a8e0-11e5-84c0-f04f17d42625.png)

yep

**Comment by zurnet** [comment]
Can you get it to run locally?

$client = new couchClient ('http://user_name:pass_word@127.0.0.1:5984','THE_DB_NAME');

?

Also, as far as I know cloudant runs without that port number,so for example:

$client = new couchClient ('https://user_name:pass_word@sub_domain.cloudant.com','the_db_name');

**Comment by 8418128** [comment]
sorry i didnt create the view but now yes, i remove the port from the url and get the same exception.
![image](https://cloud.githubusercontent.com/assets/15995221/11962658/bdc38d2a-a8e1-11e5-8cdd-96f2258bd374.png)

my user is socpa and my password is asdargonnijao, i dont care because this is for educational purposes so maybe you can help me more find out what happens.

i tried locally and it works fine.

Thanks!

**Comment by zurnet** [comment]
this works for me:

<?php
	require_once "inc/libs/PHP-on-Couch/couch.php";
	require_once "inc/libs/PHP-on-Couch/couchClient.php";
	require_once "inc/libs/PHP-on-Couch/couchDocument.php";
	require_once "inc/libs/PHP-on-Couch/couchReplicator.php";

	$client;

	$client = new couchClient ('https://socpa:asdargonnijao@socpa.cloudant.com','users');


		$db_get_recs = '';
		$db_get_recs = $client;
		$db_get_recs = $db_get_recs->include_docs(FALSE);
		$db_get_recs = $db_get_recs->asArray();
		$db_get_recs = $db_get_recs->getView('default','new-view'); 

		print_r($db_get_recs);



?>

**Comment by 8418128** [comment]
Not for me... it means that is a problem with laravel :S 
have you got any idea?

**Comment by zurnet** [comment]
sorry do not know much about laravel

**Comment by 8418128** [comment]
okey, thanks a lot man!

**Comment by 8418128** [comment]
mmm im trying to get your code outside of laravel, in xampp but i get the same exception

![image](https://cloud.githubusercontent.com/assets/15995221/11977787/3cfada90-a986-11e5-8ca0-ff13a107d75a.png)

**Comment by zurnet** [comment]
hmmm not too sure exactly... forgive me I'd have to think about it more.

**Comment by david-bojnansky** [comment]
Into .env file add:

CURLOPT_SSL_VERIFYHOST=0
CURLOPT_SSL_VERIFYPEER=0

You have to add both! I do use HTTPS but my cert is not trusted so when I added these options, everything works... 

If you have not .env file then for fast fix add these options to CouchHttpAdapterCurl::buildRequest() method...

**Comment by popojargo** [comment]
.env files are not supported in this repository.

**Comment by pimhakkert** [comment]
Be sure to set `verify_ssl_certificates = true` and `fail_if_no_peer_cert = false` in the CouchDB local.ini if you are supplying a CAcert file. Not doing so resulted in issues with verifying the peer and that broke PHP on Couch for me.
