### ISSUE TITLE
requests fails, but is accepted

### ISSUE THREAD

**Issue by zurnet** [dready92/PHP-on-Couch#57]
Don't know if anyone else has noticed this, but sometimes posting to the server, using the try/catch statement, the request comes back as 'fail'... and the server error will say 'accepted'.  In other words, the data still gets added into couchdb, but 'fails'.  I'm not sure if this is an error with the script or something funky with couchdb?

It's normally not an issue, but when I'm expecting a certain json response and instead I get back an error message, it's tough to handle it when it's still a successful add to couchdb

**Comment by zurnet** [comment]
I know this has been around for a while, anyone every find a solution to this?  In the try/catch I'm now getting an error of 'Continue (PUT)', rather than 'Accepted'.... maybe this is due to a newer version of couchdb?  Either way, I'd love to figure out how to simply get a list of the errors in the catch (possible ones) before they happen, but ideally.... if 'Accepted' and 'Continue' are successful responses, they shouldn't be in the catch no?

**Comment by zurnet** [comment]
not sure anyone is reading this anymore, but any new post to cloudant returns this error:

Uncaught exception 'couchException' with message 'Continue

its' requiring me to fix many of my applications... anyone have an idea how to fix this on the library end or do we have to deal with it in the catch statement somehow?

**Comment by popojargo** [comment]
The Continue error has been fixed. Please tell me if you're still experiencing issues.

**Comment by agon-e** [comment]
Experiencing this kind of "error" on a Debian 8 System with CouchDB 2.0.2. Exception is thrown, but says "Accepted" and everything is working as expected.

**My code:** 
`    private function setData($data){
        $doc = new \PHPOnCouch\CouchDocument($this->db);

        try {
            $doc->set($data);
            return $doc;
        } catch (\PHPOnCouch\Exceptions\CouchException $e) {
            var_dump($e);
            $this->log("Document storage failed : " . $e->getMessage());
        }

        return false;
    }`

**The var_dump of my code** 

`object(PHPOnCouch\Exceptions\CouchException)#17 (8) {
  ["couchResponse":protected]=>
  array(3) {
    ["body"]=>
    object(stdClass)#18 (3) {
      ["ok"]=>
      bool(true)
      ["id"]=>
      string(32) "87fb42ff2391f174046af49c72f8b63c"
      ["rev"]=>
      string(34) "1-9f97bf3e8431af712cc96d4fa509b7f8"
    }
    ["status_code"]=>
    string(3) "202"
    ["status_message"]=>
    string(8) "Accepted"
  }
  ["message":protected]=>
  string(40) "Accepted (POST /xxx[])"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(202)
  ["file":protected]=>
  string(106) "xxx/vendor/php-on-couch/php-on-couch/src/Exceptions/CouchException.php"
  ["line":protected]=>
  int(93)
  ["trace":"Exception":private]=>
  array(7) {
    [0]=>
    array(6) {
      ["file"]=>
      string(92) "xxx/vendor/php-on-couch/php-on-couch/src/CouchClient.php"
      ["line"]=>
      int(201)
      ["function"]=>
      string(7) "factory"
      ["class"]=>
      string(36) "PHPOnCouch\Exceptions\CouchException"
      ["type"]=>
      string(2) "::"
      ["args"]=>
      array(4) {
        [0]=>
        array(3) {
          ["body"]=>
          object(stdClass)#18 (3) {
            ["ok"]=>
            bool(true)
            ["id"]=>
            string(32) "87fb42ff2391f174046af49c72f8b63c"
            ["rev"]=>
            string(34) "1-9f97bf3e8431af712cc96d4fa509b7f8"
          }
          ["status_code"]=>
          string(3) "202"
          ["status_message"]=>
          string(8) "Accepted"
        }
        [1]=>
        string(4) "POST"
        [2]=>
        string(21) "/xxx"
        [3]=>
        array(0) {
        }
      }
    }
    [1]=>
    array(6) {
      ["file"]=>
      string(92) "xxx/vendor/php-on-couch/php-on-couch/src/CouchClient.php"
      ["line"]=>
      int(641)
      ["function"]=>
      string(12) "queryAndTest"
      ["class"]=>
      string(22) "PHPOnCouch\CouchClient"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(5) {
        [0]=>
        string(4) "POST"
        [1]=>
        string(21) "/xxx"
        [2]=>
        array(2) {
          [0]=>
          int(200)
          [1]=>
          int(201)
        }
        [3]=>
        array(0) {
        }
        [4]=>
        object(stdClass)#19 (7) {
          ["type"]=>
          string(3) "log"
          ["mess"]=>
          string(16) "xxx selftest"
          ["lvl"]=>
          int(1)
          ["ts"]=>
          int(1511806609)
          ["date"]=>
          string(14) "27.11.17 19:16"
          ["ident"]=>
          string(7) "testlog"
          ["v"]=>
          string(5) "0.9.5"
        }
      }
    }
    [2]=>
    array(6) {
      ["file"]=>
      string(94) "xxx/vendor/php-on-couch/php-on-couch/src/CouchDocument.php"
      ["line"]=>
      int(231)
      ["function"]=>
      string(8) "storeDoc"
      ["class"]=>
      string(22) "PHPOnCouch\CouchClient"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        object(stdClass)#19 (7) {
          ["type"]=>
          string(3) "log"
          ["mess"]=>
          string(16) "xxx selftest"
          ["lvl"]=>
          int(1)
          ["ts"]=>
          int(1511806609)
          ["date"]=>
          string(14) "27.11.17 19:16"
          ["ident"]=>
          string(7) "testlog"
          ["v"]=>
          string(5) "0.9.5"
        }
      }
    }
    [3]=>
    array(6) {
      ["file"]=>
      string(94) "xxx/vendor/php-on-couch/php-on-couch/src/CouchDocument.php"
      ["line"]=>
      int(272)
      ["function"]=>
      string(6) "record"
      ["class"]=>
      string(24) "PHPOnCouch\CouchDocument"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(0) {
      }
    }
    [4]=>
    array(6) {
      ["file"]=>
      string(86) "xxx/vendor/xxx/xxx/xxx/couch/xxxCouch.php"
      ["line"]=>
      int(137)
      ["function"]=>
      string(3) "set"
      ["class"]=>
      string(24) "PHPOnCouch\CouchDocument"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        object(stdClass)#12 (7) {
          ["type"]=>
          string(3) "log"
          ["mess"]=>
          string(16) "xxx selftest"
          ["lvl"]=>
          int(1)
          ["ts"]=>
          int(1511806609)
          ["date"]=>
          string(14) "27.11.17 19:16"
          ["ident"]=>
          string(7) "testlog"
          ["v"]=>
          string(5) "0.9.5"
        }
      }
    }
    [5]=>
    array(6) {
      ["file"]=>
      string(86) "xxx/vendor/xxx/xxx/xxx/couch/xxxCouch.php"
      ["line"]=>
      int(130)
      ["function"]=>
      string(7) "setData"
      ["class"]=>
      string(23) "xxx\xxx\xxxCouch"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        object(stdClass)#12 (7) {
          ["type"]=>
          string(3) "log"
          ["mess"]=>
          string(16) "xxx selftest"
          ["lvl"]=>
          int(1)
          ["ts"]=>
          int(1511806609)
          ["date"]=>
          string(14) "27.11.17 19:16"
          ["ident"]=>
          string(7) "testlog"
          ["v"]=>
          string(5) "0.9.5"
        }
      }
    }
    [6]=>
    array(6) {
      ["file"]=>
      string(72) "xxx/vendor/xxx/xxx/xxx/test.php"
      ["line"]=>
      int(14)
      ["function"]=>
      string(3) "log"
      ["class"]=>
      string(23) "xxx\xxx\xxxCouch"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(3) {
        [0]=>
        &string(16) "xxx selftest"
        [1]=>
        &int(1)
        [2]=>
        &string(7) "testlog"
      }
    }
  }
  ["previous":"Exception":private]=>
  NULL
}`

Same code on Ubuntu 14.04 and CouchDB 1.5.0 is working fine.

**Comment by popojargo** [comment]
@agon-e  Project is nowaday supported and updated by the PHP-on-Couch team : https://github.com/PHP-on-Couch/PHP-on-Couch 

Please try to use the latest version and if the error still occurs, please open  an issue on the appropriate repo
