### ISSUE TITLE
implement a mehtod for _temp_view

### ISSUE THREAD

**Issue by sebastianrakel** [dready92/PHP-on-Couch#58]
CouchDB has a function for temp Views, so you can send a function to the server and get the result, without store the view.

Example: 

```
curl -H 'Content-Type: application/json' -X POST http://localhost:5984/example/_temp_view -d '{"map" : "function(doc) { if (doc.kdnr) { emit(doc.kdnr, doc.licencse); } }"}'
```

It is possible to implement this and get an array of docs back?

**Comment by popojargo** [comment]
Not supported with CouchDB 2.0. Mention me if you feel this should be still implemented even if CouchDB doesn't support it.
