### ISSUE TITLE
Fatal error with password

### ISSUE THREAD

**Issue by drlinux** [dready92/PHP-on-Couch#61]
If the password contains @ (example: pass@word) this happens:

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'no data to parse' in /home/noname/.web/couchdbtest/lib/couch.php:138 Stack trace: #0 /home/noname/.web/couchdbtest/lib/couchClient.php(152): couch::parseRawResponse(false, false) #1 /home/noname/.web/couchdbtest/lib/couchClient.php(261): couchClient->_queryAndTest('GET', '/test', Array) #2 /home/noname/.web/couchdbtest/lib/couchClient.php(302): couchClient->getDatabaseInfos() #3 /home/noname/.web/couchdbtest/index.php(8): couchClient->databaseExists() #4 {main} thrown in /home/noname/.web/couchdbtest/lib/couch.php on line 138

Without @ (example : password) works.

**Comment by popojargo** [comment]
I'm offering support for this library if you still need it. I could fix this on my fork. @drlinux

**Comment by bhagawath** [comment]
I am also facing same issue . Could you help to fix it .

**Comment by popojargo** [comment]
> I am also facing same issue . Could you help to fix it .

Use this repo: https://github.com/PHP-on-Couch/PHP-on-Couch
