### ISSUE TITLE
change password

### ISSUE THREAD

**Issue by sidn041** [dready92/PHP-on-Couch#62]
HI There, 

is there option to change password with this API ?

Thanks
Sid

**Comment by popojargo** [comment]
@sidn041  You mean change the password of a user?

**Comment by sidn041** [comment]
Yes, when user forget the password, they should be able to reset it somehow.

**Comment by popojargo** [comment]
@sidn041 This is not natively supported with CouchDB. Therefore, I think it would be possible to provide a method to change the password on a _user document. I recently forked this project to improve the library and give support to it. If my proposition is interesting, I suggest that you create an issue on my [fork](https://github.com/popojargo/PHP-on-Couch) and we can continue to discuss about this there.

**Comment by sidn041** [comment]
@popojargo sure will create issue there, will also provide support wherever I can with testing.
