### ISSUE TITLE
CouchAdmin Construct Error

### ISSUE THREAD

**Issue by albeb89** [dready92/PHP-on-Couch#68]
It seems that the CouchAdmin class give some error on the construct.
Whe i use my client to query there's no problem, but when i create a CouchAdmin object passing the same client it gave me this:

> Bad Request - Name: '_membership'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter. (GET /_membership [])

**Comment by popojargo** [comment]
Can you share some code example?

**Comment by albeb89** [comment]
I'm using couchdb 1.6.1
here's my code
`$client = new CouchClient("http://user:password@localhost:5984","mydb");`
`if (!$client->databaseExists()) {`
`        $client->createDatabase();`
`        $admin = new CouchAdmin($client);`
`        $admin->addDatabaseAdminUser("couchuser");`
`}`

When i reach the istruction
`        $admin = new CouchAdmin($client);`
the couch db return the error:

> Bad Request - Name: '_membership'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter. (GET /_membership [])

But if i try to get some data  or insert/update it's all fine.

**Comment by popojargo** [comment]
Use this branch instead : https://github.com/popojargo/PHP-on-Couch/tree/1.6.1

**Comment by albeb89** [comment]
according to my composer.json i'm using it:
`"popojargo/php-on-couch": "1.6.1"`

**Comment by popojargo** [comment]
Can you contact me via Gitter? https://gitter.im/popojargo/PHP-on-Couch

**Comment by albeb89** [comment]
suddenly i'm going out now. Tommorow i'll write to you ;)

**Comment by popojargo** [comment]
Alright, because I'm pretty sure your composer.json is not using the correct version tag and still getting the default : master.

Take a look at your CouchAdmin.php in the __constructor. If you see a membership() call, this would confirm my hypothese.

**Comment by albeb89** [comment]
You were right, now i've switched to the correct version and then i've another error on the istruction:

`if $client->databaseExists()`

Attempted to load class "couchNotFoundException" from namespace "PHPOnCouch\Exceptions".
Did you forget a "use" statement for another namespace?

        in /code/vendor/dready92/php-on-couch/src/Exceptions/CouchException.php line 78

    at PHPOnCouch\Exceptions\CouchException::factory(array('body' => object(stdClass), 'status_code' => '404', 'status_message' => 'Object Not Found'), 'GET', '/user_test', array())
        in /code/vendor/dready92/php-on-couch/src/CouchClient.php line 168

    at PHPOnCouch\CouchClient->_queryAndTest('GET', '/user_test', array(200))
        in /code/vendor/dready92/php-on-couch/src/CouchClient.php line 291

    at PHPOnCouch\CouchClient->getDatabaseInfos()
        in /code/vendor/dready92/php-on-couch/src/CouchClient.php line 337

    at PHPOnCouch\CouchClient->databaseExists()
        in /code/src/AppBundle/Utils/CouchDB.php line 36

`

**Comment by popojargo** [comment]
For the moment, simply add the use PHPOnCouch\Exceptions.

I don't know for now how I could remove this necessary namespace requirement.
