### ISSUE TITLE
[Question] Support for indices and search on Couch 2.0 (Mango query search)

### ISSUE THREAD

**Issue by andreyvk** [dready92/PHP-on-Couch#74]
Hi @dready92 ,

Good to know that improvements to the library are ongoing. Are any plans for integrating indexing and search into the library though?

Basically we are looking for the support of `_find` and `_index`. Or is it already supported? Couldnt find any hints on that.

**Comment by popojargo** [comment]
_find and _index are not supported. I'm currently moving everything to this [repository](https://github.com/PHP-on-Couch/PHP-on-Couch) since dready92 is not supporting this current repository.

These new feature would be interesting. I will see what I can do so far in the next weeks.

**Comment by popojargo** [comment]
@andreyvk I wil try to do this in the next 2 weeks : https://github.com/PHP-on-Couch/PHP-on-Couch/pull/18
