### ISSUE TITLE
 Fatal error: Class 'PHPOnCouch\CouchClient' not found 

### ISSUE THREAD

**Issue by monahadibarhaghtalab** [dready92/PHP-on-Couch#75]
Hi 
when I try to run my php file the above error occurs, I can't even run the examples .
Please help me to solve my issue.

**Comment by monahadibarhaghtalab** [comment]
`<?php

$couch_dsn = "http://localhost:5984/";
$couch_db = "adb";


/**
 * include the library
 */


use PHPOnCouch\CouchClient;//The CouchDB client object
//    PHPOnCouch\Couch, //The core of PHP-on-Couch
//    PHPOnCouch\CouchAdmin; //The object to handle admins


$client = new  CouchClient($couch_dsn,$couch_db);

try {
    $info = $client->getDatabaseInfos();
} catch (Exception $e) {
    echo "Error:".$e->getMessage()." (errcode=".$e->getCode().")\n";
    exit(1);
}
print_r($info);


`
This is my code.

**Comment by popojargo** [comment]
Please, use the latest version available here : https://github.com/PHP-on-Couch/PHP-on-Couch
